-- ---
-- Globals
-- ---
-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;
-- ---
--
DROP TABLE IF EXISTS properties;
--
DROP TABLE IF EXISTS images;
--
CREATE TABLE properties (
  id INTEGER NOT NULL,
  small_description VARCHAR(30) NULL DEFAULT NULL,
  star_rating NUMERIC NULL DEFAULT NULL,
  review_total INTEGER NULL DEFAULT NULL,
  superhost BOOLEAN NULL DEFAULT NULL,
  city VARCHAR(50) NULL DEFAULT NULL,
  state_province VARCHAR(20) NULL DEFAULT NULL,
  country VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (id)
);
--
CREATE TABLE images (
  id INTEGER NOT NULL,
  property_id INTEGER NULL DEFAULT NULL,
  url VARCHAR(300) NULL DEFAULT NULL,
  small_description VARCHAR(30) NULL DEFAULT NULL,
  grouping INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (property_id)
);
